version: "3"

services:
  db:
    image: postgres:latest
    container_name: config-ms-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-microservice}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: config-ms-app
    volumes:
      - appdata:/app/dist/uploads/
    env_file:
      - app/.env
    ports:
      - "80:3000"
    depends_on:
      - db

volumes:
  dbdata:
  appdata: